author = "BRAF Team"
mainprefix = "braf"
name = "Brazilian Armed Forces Mod - Factions"
prefix = "braf_factions"

[version]
path = "addons/main/script_version.hpp" # Default

build = 1 # Optional
major = 2 # Overrides path when set
minor = 0 
patch = 0 

git_hash = 0 # Default: 8

[files]
exclude = [
  "source/*",
  "*.png",
  "*.tga",
  "*.psd",
  "*.fbx",
  "*.obj",
]

[properties]
author = "BRAF Team"
url = "https://www.brafmod.com.br/"

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
  "450814997", # CBA_A3
  "2223739438", # BRAF Mod (Public Version)
]
