name: Release

on:
  push:
    branches:
    - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Check Strings
      run: python3 tools/check_strings.py
    - name: Check for BOM
      uses: arma-actions/bom-check@v1

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives

  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Run HEMTT release
      run: hemtt release
    - name: Rename build folder
      run: mv .hemttout/release .hemttout/@braf_factions
    - name: Upload to Steam Workshop (DEV)
      uses: actions/upload-artifact@v3
      with:
        name: braf_factions_${{ github.sha }}
        path: .hemttout/@*
    - uses: arma-actions/workshop-upload@v1
      with:
        appId: '107410'    # default
        itemId: '2740442349' # Id of item to update
        contentPath: '@braf_factions'
        changelog: 'Version ${{ env.VERSION }} update'
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
